EMSDK_PATH         ?= ../../emsdk
EMSCRIPTEN_PATH    ?= $(EMSDK_PATH)/upstream/emscripten
CLANG_PATH          = $(EMSDK_PATH)/upstream/bin
PYTHON_PATH         = /usr/bin/python3
NODE_PATH           = $(EMSDK_PATH)/node/12.9.1_64bit/bin
PATH = $(shell printenv PATH):$(EMSDK_PATH):$(EMSCRIPTEN_PATH):$(CLANG_PATH):$(NODE_PATH):$(PYTHON_PATH)
all:
	make PLATFORM=PLATFORM_WEB -B
